title = "AlexNet MNIST Example"

[datasets]
[datasets.mnist] # name of dataset folder under 'datasets' folder
loadfname = "custom_load" # filename that contains the data load functions under datasets/mnist/ folder
loadobj = "MNIST"         # class name of dataset

[models]
[models.alexnet_model] #name of python script under 'models' folder
modelname = "mymodel"

[testcases]
[testcases.demo_testcase] # name of testcase to run under 'testcases' folder
testfunc = "mytest"         # function name of testcase
testsize = 0.3              # 70% training 30% testing #custom testconfig param
epochs = 3                  # custom testconfig param
optimizer = 'adam'          # custom optimizer
detailed_comparison = true # whether detailed comparison is used


[[testrun]]
dataset = "mnist"
model = "alexnet_model"
testcase = "alexnet_mnist_testcase"
out_format = ["json"]