title = "AlexNet MNIST Example"

[datasets]
[datasets.mnist] # name of dataset folder under 'datasets' folder
loadfname = "custom_load" # filename that contains the data load functions under datasets/mnist/ folder
loadobj = "MNIST"         # class name of dataset

[models]
[models.alexnet_model] #name of python script under 'models' folder
modelname = "mymodel"

[testcases]
[testcases.alexnet_mnist_testcase] # name of testcase to run under 'testcases' folder
testfunc = "alexnet_mnist_testcase" # function name of testcase
testsize = 0.2                      # 20% testing #custom testconfig param
validsize = 0.125                   # 80%*12.5%=10% testing #custom testconfig param
epochs = 3                          # custom testconfig param
optimizer = 'adam'                  # custom optimizer
detailed_comparison = true          # whether detailed comparison is used
batch_size = 100                    # image size of each batch
input_shape = [224,224]
num_classes = 10


[[testrun]]
dataset = "mnist"
model = "alexnet_model"
testcase = "alexnet_mnist_testcase"
out_format = ["json"]
