title = "Demo MNIST Example" # test run title

[datasets]
[datasets.mnist] # name of dataset folder under 'datasets' folder
loadfname = "custom_load" # filename that contains the data load functions under datasets/mnist/ folder
loadobj = "MNIST"         # class name of dataset

[models]
[models.mnist_demo_model] # name of python script under 'models' folder
modelname = "mymodel" # variable name of model

[testcases]
[testcases.demo_testcase] # name of testcase to run under 'testcases' folder
testfunc = "mytest"         # function name of testcase
validsize = 0.15                   # 15% of training data #custom testconfig param
epochs = 1                  # custom testconfig param
optimizer = 'sgd'                  # custom optimizer adam/sgd
sgd_learning_rate = 0.01            # sgd learning rate
sgd_momentum = 0.1                  # sgd momentum
dump_err_img = true # whether detailed comparison is used


[[testrun]]
dataset = "mnist"          # dataset name
model = "mnist_demo_model" # model name
testcase = "demo_testcase" # testcase name
out_format = ["json"]      # output format, only json supported for now