title = "Demo MNIST Example"

[datasets]
[datasets.mnist]  #name of dataset folder under 'datasets' folder
x_name = "jpg_images"
x_format = "jpg"
y_name = "y_numbers"
y_format = "npy"

[models]
[models.mnist_demo_model] #name of python script under 'models' folder
modelname = "mymodel"

[testcases]
[testcases.demo_testcase] #name of testcase to run under 'testcases' folder
testfunc = "mytest"
test_train_ratio = [0.7,0.3] # 70% training 30% testing 

[[testrun]]
dataset = "mnist"
model = "mnist_demo_model"
testcase = "demo_testcase"