title = "LeNet MNIST Example"

[datasets]
[datasets.mnist] # name of dataset folder under 'datasets' folder
loadfname = "custom_load" # filename that contains the data load functions under datasets/mnist/ folder
loadobj = "MNIST"         # class name of dataset

[models]
[models.lenet_model] #name of python script under 'models' folder
modelname = "mymodel"

[testcases]
[testcases.demo_testcase] # name of testcase to run under 'testcases' folder
testfunc = "mytest"        # function name of testcase
testsize = 0.2                      # 20% testing #custom testconfig param
validsize = 0.15                   # 15% of training data #custom testconfig param
epochs = 3                 # custom testconfig param
detailed_comparison = true # whether detailed comparison is used
trial_img_no = 10           # dump 10 images out as trial
optimizer = 'sgd'           # custom optimizer adam/sgd
sgd_learning_rate = 0.01    # sgd learning rate
sgd_momentum = 0.1          # sgd momentum

[[testrun]]
dataset = "mnist"
model = "lenet_model"
testcase = "demo_testcase"
out_format = ["json"]