title = "LeNet MNIST Example"

[datasets]
[datasets.mnist]  #name of dataset folder under 'datasets' folder
x_name = "jpg_images"
x_format = "load_normal_images"
y_name = "y_numbers"
y_format = "load_npy"

[models]
[models.lenet_model] #name of python script under 'models' folder
modelname = "mymodel"

[testcases]
[testcases.demo_testcase] #name of testcase to run under 'testcases' folder
testfunc = "mytest"
testsize = 0.3 # 70% training 30% testing 
epochs = 6

[[testrun]]
dataset = "mnist"
model = "lenet_model"
testcase = "demo_testcase"
out_format = ["json"]