title = "MaskRCNN Example"

[datasets]
[datasets.lolimg]  #name of dataset folder under 'datasets' folder
loadfname = "custom_load"
loadobj = "TextImgLoader"

[datasets.textimg]  #name of dataset folder under 'datasets' folder
loadfname = "custom_load"
loadobj = "TextImgLoader"

[models]
[models.mask_rcnn_model] #name of python script under 'models' folder
modelname = "mymodel"

[testcases]
[testcases.mask_rcnn_testcase] #name of testcase to run under 'testcases' folder
testfunc = "mytest"
num_classes = 2 #BG,TEXT
input_shape = [512,512,3] #H,W,C
IMAGE_RESIZE_MODE = "square"
# square: Resize and pad with zeros to get a square image of size [max_dim, max_dim].
IMAGE_MIN_DIM = 512 #set consistent with input shape
IMAGE_MAX_DIM = 512 #set consistent with input shape
# Minimum scaling ratio. Checked after MIN_IMAGE_DIM and can force further
# up scaling. For example, if set to 2 then images are scaled up to double
# the width and height, or more, even if MIN_IMAGE_DIM doesn't require it.
# However, in 'square' mode, it can be overruled by IMAGE_MAX_DIM.
IMAGE_MIN_SCALE = 0

### training params
shuffle = true
batch_size = 1
epochs = 48 #8
steps_per_epoch = 2000 #1000
validation_steps = 200 #100
### optimizer
learning_rate = 0.0016
momentum = 0.374
gradient_clip_norm = 2.0


### others
# How many anchors per image to use for RPN training
RPN_TRAIN_ANCHORS_PER_IMAGE = 512 #512
RPN_BBOX_STD_DEV = [0.1, 0.1, 0.2, 0.2]
# Maximum number of ground truth instances to use in one image
MAX_GT_INSTANCES = 256 #100
# Image mean (RGB) TODO: update according to image set
MEAN_PIXEL = [123.7, 116.8, 103.9]
# Weight decay regularization # not used for now
WEIGHT_DECAY = 0.0001
# Loss weights for more precise optimization.
LOSS_WEIGHTS = {"rpn_class_loss" = 12.0,"rpn_bbox_loss" = 9.0,"mrcnn_class_loss" = 6.0,"mrcnn_bbox_loss" = 3.0,"mrcnn_mask_loss" = 1.0}
# Number of ROIs per image to feed to classifier/mask heads
TRAIN_ROIS_PER_IMAGE = 512
# Percent of positive ROIs used to train classifier/mask heads
ROI_POSITIVE_RATIO = 0.5
# ANCHOR_AREAS
ANCHOR_AREAS = [16,25,36,49,64]
# ASPECT_RATIOS
ASPECT_RATIOS = [[1,4],[1,3],[1,2],[1,1],[2,1],[3,1],[4,1]] #w,h
# ANCHOR_STRIDE
ANCHOR_STRIDE = 1
# POS_IOU_THRES
POS_IOU_THRES = 0.4
# RPN_NMS_THRESHOLD
RPN_NMS_THRESHOLD = 0.4


[[testrun]]
dataset = "lolimg"
# dataset = "textimg"
model = "mask_rcnn_model"
testcase = "mask_rcnn_testcase"
out_format = ["json"]