title = "NiN CIFAR Example"

[datasets]
[datasets.cifar]  #name of dataset folder under 'datasets' folder
loadfname = "custom_load"
loadobj = "load_cifar10"

[models]
[models.nin_model] #name of python script under 'models' folder
modelname = "mymodel"

[testcases]
[testcases.cifar_testcase] #name of testcase to run under 'testcases' folder
testfunc = "mytest"
validsize = 0.1
epochs = 10
batch_size = 64
input_shape = [224,224,3] #H,W,C
test_batch_size = 1024
train_batch_size = 1024
trial_img_no = 10


[[testrun]]
dataset = "cifar"
model = "nin_model"
testcase = "cifar_testcase"
out_format = ["json"]