title = "VGG16 CIFAR Example"

[datasets]
[datasets.cifar]  #name of dataset folder under 'datasets' folder
loadfname = "custom_load"
loadobj = "load_cifar10"

[models]
[models.vgg16_model] #name of python script under 'models' folder
modelname = "mymodel"

[testcases]
[testcases.cifar_testcase] #name of testcase to run under 'testcases' folder
testfunc = "mytest"
validsize = 0.15                   # 15% of training data #custom testconfig param
epochs = 10
batch_size = 64
input_shape = [224,224,3] #H,W,C
test_batch_size = 256
train_batch_size = 256
trial_img_no = 10           # dump 10 images out as trial
optimizer = 'sgd'           # custom optimizer adam/sgd
sgd_learning_rate = 0.01    # sgd learning rate
sgd_momentum = 0.1          # sgd momentum


[[testrun]]
dataset = "cifar"
model = "vgg16_model"
testcase = "cifar_testcase"
out_format = ["json"]